spring:
  application:
    name: invoice
  datasource:
    url: jdbc:postgresql:///invoice_db?cloudSqlInstance=hellogrpc-296603:us-central1:invoice&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=invoice
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  profiles:
    active: development

server:
  port: 8080

circle:
  api:
    base-url: https://api-sandbox.circle.com
    key: ${CIRCLE_API_KEY:your-sandbox-api-key}
  webhook:
    secret: ${CIRCLE_WEBHOOK_SECRET:your-webhook-secret}

logging:
  level:
    com.invoice: DEBUG
    org.springframework.web: DEBUG
